apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: ahbn-peer
  ports:
    - name: grpc
      port: {{ .Values.grpcPort }}
      targetPort: {{ .Values.grpcPort }}