apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: peer
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Values.service.name }}
  replicas: {{ .Values.numNodes }}
  selector:
    matchLabels:
      app: ahbn-peer
  template:
    metadata:
      labels:
        app: ahbn-peer
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: peer
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.grpcPort }}
          env:
            - name: TOPOLOGY_PATH
              value: /config/topology.json
            - name: GRPC_PORT
              value: "{{ .Values.grpcPort }}"
            - name: PEER_SERVICE_NAME
              value: {{ .Values.service.name | quote }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: ahbn-topology